### ISSUE TITLE
Docker Compose Error

### ISSUE THREAD

**Issue by iburnaga** [indentlabs/notebook#277]
### Expected behavior
Docker-compose up should put up local site.
### Actual behavior
Warning: the running version of Bundler (1.13.6) is older than the version that created the lockfile (1.16.2). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
Your Ruby version is 2.3.1, but your Gemfile specified ~> 2.5
ERROR: Service 'web' failed to build: The command '/bin/sh -c bundle install' returned a non-zero code: 18

Ruby version improper.
### Steps to reproduce the behavior
Use Docker-compose up on windows 10 pro

**Comment by tristanil** [comment]
Thanks for this report. I don't have a Windows machine to reproduce this, but it should be fixed in https://github.com/indentlabs/notebook/pull/280. Would you mind confirming?

**Comment by SethX3** [comment]
Just as a general update:
The issue persists when using the `master` branch.

```bash
Warning: the running version of Bundler (1.16.6) is older than the version that created the lockfile (1.17.3). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
Your Ruby version is 2.5.1, but your Gemfile specified ~> 2.6
ERROR: Service 'web' failed to build: The command '/bin/sh -c bundle install' returned a non-zero code: 18
```

When using the tag v3.1.0, this problem does not occur.

**Comment by drusepth** [comment]
Thanks for the update. We've upgraded Ruby since the above fix, and the new version wasn't updated in the Dockerfile. https://github.com/indentlabs/notebook/pull/572/commits/04f236b0c2e3e426d55840e75754566e2a5e1622 (releasing tonight) should fix the issue, but you can always make the change yourself locally to get it fixed sooner.

**Comment by SethiPandi** [comment]
I believe this issue has already been resolved, could it be closed by any chance?

(There are still some problems with Docker, but this isn't one at least. The Dockerfile and docker-compose.yml can build Notebook.ai successfully and that error no longer occurs.)
